######################################################################
# Automatically generated by qmake (3.0) Wed Dec 3 10:27:17 2014
######################################################################

TEMPLATE = app
TARGET = tableview
INCLUDEPATH += .
# Need to add this next line, then rerun "qmake".
#QT = core gui widgets
QT = core gui
CONFIG += console

# Input
HEADERS += EwWidget.hh TableView.hh TableModel.hh
SOURCES += main.cc EwWidget.cc TableView.cc TableModel.cc
