######################################################################
# Automatically generated by qmake (3.0) Wed Dec 3 10:27:17 2014
######################################################################

TEMPLATE = app
TARGET = tableview
INCLUDEPATH += .
# Need to add this next line, then rerun "qmake".
QT = core gui widgets

# Input
HEADERS += TableModel.hh
SOURCES += main.cc TableModel.cc
