######################################################################
# Automatically generated by qmake (3.0) Wed Dec 3 10:27:17 2014
######################################################################

TEMPLATE = app
TARGET = tableview
INCLUDEPATH += .
# Need to add this next line, then rerun "qmake".
QT = core gui widgets
CONFIG += console

# Input
HEADERS += TableView.hh TableModel.hh
SOURCES += main.cc TableView.cc TableModel.cc
